import bpy


class TextToSpeechSettings(bpy.types.PropertyGroup):

    #    pitch : bpy.props.FloatProperty(
    #        name="Pitch",
    #        description="Control pitch",
    #        default=1.0,
    #        min=0.1,
    #        max=10.0)

    accent_enumerator: bpy.props.EnumProperty(
        name="",
        description="Accent must match the language setting to work",
        items=[('0', "English Australia", ""),
               ('1', "English United Kingdom", ""),
               ('2', "English Canada", ""),
               ('3', "English America", ""),               
               ('4', "English India", ""),
               ('5', "English Ireland", ""),
               ('6', "English South Africa", ""),
               ('7', "French Canada", ""),
               ('8', "French France", ""),
               ('9', "Portuguese Brazil", ""),
               ('10', "Portuguese Portugal", ""),
               ('11', "Spanish Mexico", ""),
               ('12', "Spanish Spain", ""),
               ('13', "Spanish US)", "")])

    language_enumerator: bpy.props.EnumProperty(
        name="",
        description="Language options",
        items=[('1', "Afrikaans", ""),
               ('2', "Albanian", ""),
               ('3', "Arabic", ""),
               ('4', "Armenian", ""),
               ('5', "Bangla", ""),
               ('6', "Bosnian", ""),
               ('7', "Bulgarian", ""),
               ('8', "Burmese", ""),
               ('9', "Catalan", ""),
               ('10', "Chinese Simplified", ""),
               ('11', "Chinese Traditional", ""),
               ('12', "Croatian", ""),
               ('13', "Czech", ""),
               ('14', "Danish", ""),
               ('15', "Dutch", ""),
               ('16', "English", ""),
               ('17', "Esperanto", ""),
               ('18', "Estonian", ""),
               ('19', "Filipino", ""),
               ('20', "Finnish", ""),
               ('21', "French", ""),
               ('22', "German ", ""),
               ('23', "Greek", ""),
               ('24', "Gujarati", ""),
               ('25', "Hindi", ""),
               ('26', "Hungarian", ""),
               ('27', "Icelandic", ""),
               ('28', "Indonesian", ""),
               ('29', "Italian", ""),
               ('30', "Japanese", ""),
               ('31', "Javanese", ""),
               ('32', "Kannada", ""),
               ('33', "Khmer", ""),
               ('34', "Korean", ""),
               ('35', "Latin", ""),
               ('36', "Latvian", ""),
               ('37', "Macedonian", ""),
               ('38', "Malay", ""),
               ('39', "Malayalam", ""),
               ('40', "Marathi", ""),
               ('41', "Nepali", ""),
               ('42', "Norwegian", ""),
               ('43', "Polish", ""),
               ('44', "Portuguese", ""),
               ('45', "Romanian", ""),
               ('46', "Russian", ""),
               ('47', "Serbian", ""),
               ('48', "Sinhala", ""),
               ('49', "Slovak", ""),
               ('50', "Spanish", ""),
               ('51', "Sudanese", ""),
               ('52', "Swahili", ""),
               ('53', "Swedish", ""),
               ('54', "Tamil", ""),
               ('55', "Telugu", ""),
               ('56', "Thai", ""),
               ('57', "Turkish", ""),
               ('58', "Ukranian", ""),
               ('59', "Urdu", ""),
               ('60', "Vietnamese", ""),
               ('61', "Welsh", "")],
               default=('16'))
